### ISSUE TITLE
 Laravel version

### ISSUE THREAD

**Issue by barbarossa95** [balping/laravel-hashslug#2]
I can't get version 1.0.3, cause in one of last commits this branch starts requires illuminate/database 5.5.* . It is possible to get version 1.0.3 with latest bug fixes (invalid slug) or this package don't support laravel 5.4 anymore?
`- balping/laravel-hashslug 1.0.3 requires illuminate/database 5.5.* -> satisfiable by illuminate/database[5.5.x-dev] but these conflict with your requirements or minimum-stability`

**Comment by AaronBClark** [comment]
I have this same issue. Upgrading to 5.5 is not an option at the moment, and I would very much like to use this package this week. An immediate patch would be much appreciated!

**Comment by barbarossa95** [comment]
Temporary solution it is use commit hash as version tag like this
`composer require balping/laravel-hashslug:1.0.x-dev#18216f31e41de36c0b39d3a160960cc70262fa08`
It is help me for a while, we are waiting new patch

**Comment by balping** [comment]
I won't have access to my PC until Tuesday, you'll have to wait until then. Sorry for this

**Comment by balping** [comment]
Now I see, by mistake I merged back composer.json to 1.0 branch too, I only intended to merge the bugfix back. But I really wont be able to fix & test this on my mobile while having poor wifi connection, so please wait.

**Comment by balping** [comment]
Now it should be, there has been a new release. It turned out that the problem wasn't with merging things but making a release on a wrong branch.
