### ISSUE TITLE
Slug length in config

### ISSUE THREAD

**Issue by lukaszflorczak** [balping/laravel-hashslug#3]
Hey! Is it possible to set `$minSlugLength` in config file? I want to use it in multiple models and don't want to define it each time. 

For example:

```php
return [
    'appsalt' => 'your-application-salt',
    'length' => 8,
    'alphabet' => 'abcdefghijklmnopqrstuvwxyz',
];
```

Coudl you add this feature?

**Comment by balping** [comment]
Yeah, it's not a big thing, I will

**Comment by pet1330** [comment]
@balping, I cannot seem to get this to work. I have updated to 1.0.6, but when I remove the `$minSlugLength` from my model and set it in my `config/hashslug.php` it does not work. I have tried clearing my cache to ensure it's not that. Is there anything else that I have forgotten to do?

**Comment by balping** [comment]
Maybe there should be no capital letters in a config key. I'll test it when I'll be able to

**Comment by pet1330** [comment]
I think the issue may have been on my end as it is now working. Sorry!
