### ISSUE TITLE
Return slug by Controller

### ISSUE THREAD

**Issue by lukaszflorczak** [balping/laravel-hashslug#4]
I have a second question. I'm building API based on Laravel and I would like to return objects with hashed `slug` instead `id`. How can I do it?

```js
data : {
    id: 'H4sh3dSlu9',
    email: 'user@email.com',
    created_at: '...',
    updated_at: '...',
}
```

**Comment by balping** [comment]
In my own project, I use fractal transformers for this, but you could try Laravel's new [resource response](https://laravel.com/docs/5.5/eloquent-resources#resource-responses) feature, which is kind of similar to what fractal does.
