### ISSUE TITLE
Should create a default config file

### ISSUE THREAD

**Issue by iflamed** [balping/laravel-hashslug#5]
https://github.com/balping/laravel-hashslug/blob/5b0f3ce69895873547f7aa5ca31101bd1ba5fdac/src/HasHashSlug.php#L64

The env function will work at laravel debug environment but not work when laravel running at production.

**Comment by iflamed** [comment]
```php
<?php

return [
    'appsalt' => env('APP_KEY')
];

```
**This code will compatible with the history releases.**

**Comment by balping** [comment]
I just tested it with `APP_ENV=production` and still works. The env function doesn't require local environment.

**Comment by iflamed** [comment]
In production mode, The env function will not work after run `php artisan config:cache`
![image](https://user-images.githubusercontent.com/1819687/35633392-11bd4a12-06e4-11e8-93c1-660b14b59264.png)

**Comment by balping** [comment]
Thanks for pointing this out. The fix is released.
