### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by sarfraznawaz2005** [balping/laravel-hashslug#6]
I added `use HasHashSlug;` to my `Task` model. I can see hashids being generated fine in urls, however when I go to edit page of the model, it gives error:

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hashslug' in 'where clause' (SQL: select * from `tasks` where `hashslug` = Eby7m limit 1)

I am using implicit model binding.

Can you please tell what I am missing here other than adding `use HasHashSlug;` to my model ?

**Comment by balping** [comment]
Hello

What version of Laravel do you use?

Does it work with the show method?

**Comment by sarfraznawaz2005** [comment]
I am using 5.5 and I am using the `show` method, that's where it gives me error. Also gives error on `edit` method with `public function edit(Task $task)`

**Comment by balping** [comment]
How does the relevant part of your route file look like?

**Comment by sarfraznawaz2005** [comment]
Here is how:

![image](https://user-images.githubusercontent.com/201788/35778485-8d94113a-09e0-11e8-9ecc-a3c1a1a02720.png)

Here is complete method:

````
    // edit page
    public function edit(Task $task)
    {
        title('Edit Task');

        return view('task::pages.task.edit', compact('task'));
    }
````

**Comment by balping** [comment]
Are you using `Route::resource` ?

**Comment by sarfraznawaz2005** [comment]
That's true.

**Comment by balping** [comment]
Is the `SubstituteBindings` middleware loaded?

**Comment by sarfraznawaz2005** [comment]
How can i verify that ? I only added `use HasHashSlug;` to my model, did nothing else.

**Comment by balping** [comment]
One way to make it sure is putting a dummy echo or `dd()` to the handle method of `vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php`

**Comment by sarfraznawaz2005** [comment]
Yes it is being called when i put dd there.

**Comment by balping** [comment]
Then I honestly have no idea, it's some laravel weirdness, maybe some interference with laravel modules.

Use this format, this will work for sure:

```php
public function show($slug){
    $task = Task:findBySlugOrFail($slug);
}
```

**Comment by sarfraznawaz2005** [comment]
No problem, thanks, yes maybe laravel modules package is doing something weiried. FYI, I was using this package in my laravel starter here: https://github.com/sarfraznawaz2005/laravel55-starter

Maybe you should try on fresh installation of Laravel 5.5, could be issue with 5.5.

**Comment by sarfraznawaz2005** [comment]
Verified that it works with fresh installation of Laravel, so some other package I am using is doing the trick. Thanks for your help anyways.

**Comment by sarfraznawaz2005** [comment]
Found out, I was using FakeID package previously: https://github.com/Propaganistas/Laravel-FakeId and I forgot to remove its service provider registration. Thanks
