### ISSUE TITLE
Accessor

### ISSUE THREAD

**Issue by GGH-Bortels** [balping/laravel-hashslug#9]
Hey,

Really cool package!
But I miss a custom accessor for the slug. 
Look at this example: `Model::all()->pluck('name', 'slug');`
I won't work. Because slug is just a function. I modified your package and added
```
public function getHashidAttribute() {
    return $this->slug();
}
```
With that I can simply `Model::all()->pluck('name', 'hashid');`
What do you think about it?

**Comment by balping** [comment]
Hi!

Yes, this is good, but I don't think it needs to be included by default. If someone needs this, it can be added to a model under a minute. I might include this in the readme though. Thanks.
